#cloud-config
# Digital Ocean Cloud-Init Script for Open WebUI Deployment
#
# This script sets up a secure deployment user during droplet creation.
# Use this as "User Data" when creating your Digital Ocean droplet.
#
# BEFORE USING:
# 1. Replace YOUR_SSH_PUBLIC_KEY_HERE with your actual SSH public key
# 2. Optional: Change username from 'deployer' to your preference

users:
  - name: deployer
    groups: sudo, docker
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - YOUR_SSH_PUBLIC_KEY_HERE  # Replace with your SSH public key

# System updates and package installation
package_update: true
package_upgrade: true

packages:
  - git
  - curl
  - wget
  - certbot
  - jq
  - htop
  - tree
  - net-tools

# Ensure Docker service is enabled and started
runcmd:
  # Add deployer to docker group (redundant but ensures it's set)
  - usermod -aG docker deployer

  # Clone Open WebUI repository to deployer's home
  - sudo -u deployer git clone https://github.com/imagicrafter/open-webui.git /home/deployer/open-webui

  # Set ownership
  - chown -R deployer:deployer /home/deployer/open-webui

  # Create common directories
  - mkdir -p /opt/openwebui-nginx
  - chown -R deployer:deployer /opt/openwebui-nginx

  # Restart Docker to ensure group changes take effect
  - systemctl restart docker

  # Create welcome message
  - |
    cat > /home/deployer/WELCOME.txt << 'EOF'
    ╔════════════════════════════════════════════════════════════╗
    ║          Open WebUI Deployment Server Ready                ║
    ╚════════════════════════════════════════════════════════════╝

    Your server is configured and ready for Open WebUI deployment!

    Quick Start:
    1. SSH as deployer: ssh deployer@YOUR_DROPLET_IP
    2. Navigate to repo: cd ~/open-webui/mt/nginx-container
    3. Deploy nginx: ./deploy-nginx-container.sh
    4. Create client: cd ~/open-webui/mt && ./client-manager.sh

    Repository location: /home/deployer/open-webui
    User: deployer (has sudo and docker access)

    Documentation:
    - Quick Start: ~/open-webui/mt/QUICKSTART-FRESH-DEPLOYMENT.md
    - nginx Setup: ~/open-webui/mt/nginx-container/README.md

    Check Docker status: docker ps
    Check nginx container: docker ps --filter "name=openwebui-nginx"

    For security, root SSH login is disabled after first boot.
    Always use 'deployer' user for deployments.
    EOF

  - chown deployer:deployer /home/deployer/WELCOME.txt

# Disable root SSH login for security (after cloud-init completes)
bootcmd:
  - sed -i 's/^PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config || true

# Final message logged to console
final_message: |
  ╔════════════════════════════════════════════════════════════╗
  ║          Cloud-Init Setup Complete                         ║
  ╚════════════════════════════════════════════════════════════╝

  Open WebUI deployment server is ready!

  SSH as deployer: ssh deployer@YOUR_DROPLET_IP
  Read welcome message: cat ~/WELCOME.txt

  System is configured with:
  - User 'deployer' (sudo + docker access)
  - Open WebUI repository cloned
  - Docker ready
  - Certbot installed

  Root SSH login is disabled for security.
