#cloud-config
# Minimal Cloud-Init for Open WebUI
# Just clones the repo and leaves setup script ready to run

package_update: true
package_upgrade: true

packages:
  - git
  - curl

runcmd:
  - git clone https://github.com/imagicrafter/open-webui.git /root/open-webui
  - chmod +x /root/open-webui/mt/setup/create-deployment-user.sh
  - |
    cat > /root/README-NEXT-STEPS.txt << 'EOF'
    ================================================================
    Open WebUI Repository Ready!
    ================================================================

    The repository has been cloned to: /root/open-webui

    NEXT STEP: Run the setup script to create your deployment user

    Run this command:

        /root/open-webui/mt/setup/create-deployment-user.sh

    This will:
    - Create 'qbmgr' user with sudo and docker access
    - Set up SSH key for password-less login
    - Clone repo to /home/qbmgr/open-webui
    - Start the client manager for you

    Then you can exit and SSH as qbmgr:
        ssh qbmgr@YOUR_DROPLET_IP

    ================================================================
    EOF
  - cat /root/README-NEXT-STEPS.txt

final_message: |
  Repository cloned! SSH as root and run:
  /root/open-webui/mt/setup/create-deployment-user.sh
