#cloud-config
# Digital Ocean Cloud-Init Script for Open WebUI Deployment
#
# This script sets up a secure deployment user during droplet creation.
# Use this as "User Data" when creating your Digital Ocean droplet.
#
# BEFORE USING:
# 1. Replace YOUR_SSH_PUBLIC_KEY_HERE with your actual SSH public key
# 2. Optional: Change username from 'qbmgr' to your preference

users:
  - name: qbmgr
    groups: sudo, docker
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - sh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDl77XDmQLqSPiMynr48sBbEn95w7wse+Y4MYCEyfnkhUAnr3BaJFw34C92F0uJBUDa9PaTKIAkhJhuQtM+st7zkUkeSp9/CPrNVhwkQVWny+B7+kuBGBIgZfdO00W4AUp9O6NF69ABz1WYwpdCpaUKI2FgMv0HKxq7JJ/zXpjDNiTtA2MYSd6yLJ9lmdYscs6RJbUWrOQ3ILcXOn+1CYJvfSdGAaBiHbgMnU4dE1H6V8f/YrJYxDljhhktlm2/H4NZKtG9QX4R7R2hh3PKwDK1cQ8DoQ09B6oZuRbj5sk+kUulOFZz/CCG2JHX+/7ujl322P5BEPloFsFH84TI90egBIu0Of0FLtTzPSnILRcAWx02EDFH65UN7HT+Eb6JtxrkBv+kbPLa5i3v2a3YdeDyZtPbBg5LBBQteGk+ijKQLvhrXhj4VhjBeTD7IyYlSBzfg583nY/XC7zAj2Qkq+xTxNq3Juu8S9zmOjmUbluYcEkGFg8DGp17HYfLCadf/Pc= justinmartin@Justins-MacBook-Pro.local

package_update: true
package_upgrade: true

packages:
  - git
  - curl
  - wget
  - certbot
  - jq
  - htop
  - tree
  - net-tools

runcmd:
  - usermod -aG docker qbmgr
  - sudo -u qbmgr git clone https://github.com/imagicrafter/open-webui.git /home/qbmgr/open-webui
  - chown -R qbmgr:qbmgr /home/qbmgr/open-webui
  - mkdir -p /opt/openwebui-nginx
  - chown -R qbmgr:qbmgr /opt/openwebui-nginx
  - systemctl restart docker
  - |
    cat > /home/qbmgr/WELCOME.txt << 'EOF'
    Open WebUI Deployment Server Ready

    Your server is configured and ready for Open WebUI deployment!

    Quick Start:
    1. SSH as qbmgr: ssh qbmgr@YOUR_DROPLET_IP
    2. Navigate to repo: cd ~/open-webui/mt/nginx-container
    3. Deploy nginx: ./deploy-nginx-container.sh
    4. Create client: cd ~/open-webui/mt && ./client-manager.sh

    Repository location: /home/qbmgr/open-webui
    User: qbmgr (has sudo and docker access)

    Documentation:
    - Quick Start: ~/open-webui/mt/QUICKSTART-FRESH-DEPLOYMENT.md
    - nginx Setup: ~/open-webui/mt/nginx-container/README.md

    Check Docker status: docker ps
    Check nginx container: docker ps --filter "name=openwebui-nginx"

    For security, root SSH login is disabled after first boot.
    Always use 'qbmgr' user for deployments.
    EOF
  - chown qbmgr:qbmgr /home/qbmgr/WELCOME.txt
  - sed -i 's/^PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config || true

final_message: |
  Cloud-Init Setup Complete

  Open WebUI deployment server is ready!

  SSH as qbmgr: ssh qbmgr@YOUR_DROPLET_IP
  Read welcome message: cat ~/WELCOME.txt

  System is configured with:
  - User 'qbmgr' (sudo + docker access)
  - Open WebUI repository cloned
  - Docker ready
  - Certbot installed

  Root SSH login is disabled for security.
